/** Search regression checks in a real editor, using an isolated profile and document. */
const { app, BrowserWindow } = require('electron')
const fs = require('node:fs/promises')
const path = require('node:path')
const assert = require('node:assert/strict')
const OUT = path.resolve(process.argv[2] || 'design-review/round-search')
require('node:fs').mkdirSync(OUT, { recursive: true })
app.setPath('userData', path.join(OUT, 'profile'))
app.setPath('documents', OUT)
require(path.resolve(__dirname, '../out/main/index.js'))
const wait = ms => new Promise(resolve => setTimeout(resolve, ms))

async function main() {
  for (let i = 0; i < 60 && !BrowserWindow.getAllWindows().length; i++) await wait(100)
  const win = BrowserWindow.getAllWindows()[0]
  const run = code => win.webContents.executeJavaScript(code, true)
  const ctx = 'window.__mdview.editorContext()'
  const errors = []
  win.webContents.on('console-message', (_event, level, message) => { if (level >= 3) errors.push(message) })
  const press = async (keyCode, modifiers = []) => {
    win.webContents.sendInputEvent({ type: 'keyDown', keyCode, modifiers })
    win.webContents.sendInputEvent({ type: 'keyUp', keyCode, modifiers })
    await wait(120)
  }
  const field = async (name, value) => {
    await run(`(() => { const el = document.querySelector('.cm-search input[name=${name}]'); el.focus(); el.value = ${JSON.stringify(value)}; el.dispatchEvent(new Event('change', {bubbles:true})) })()`)
    await wait(120)
  }
  const button = async name => { await run(`document.querySelector('.cm-search button[name=${name}]').click()`); await wait(120) }
  const settings = async patch => { await run(`window.__mdview.setSettings(${JSON.stringify(patch)})`); await wait(180) }
  const shot = async name => fs.writeFile(path.join(OUT, name + '.png'), (await win.webContents.capturePage()).toPNG())
  const source = '# 查找与替换测试\n\n苹果 apple Apple pineapple\n\n苹果可以逐个替换，也可以全部替换。\n\n| 水果 | 数量 |\n| --- | --- |\n| 苹果 | 3 |\n\n```js\nconst apple = 123\n```\n\n[链接](./apple.md)\n\n试试 Ctrl+F 查找、Ctrl+H 替换，F3 下一个、Shift+F3 上一个，Esc 关闭。\n'
  const docDir = path.join(OUT, '查找与替换测试')
  const docPath = path.join(docDir, '查找与替换测试.md')
  await fs.mkdir(path.join(docDir, '查找与替换测试_img'), { recursive: true })
  await fs.writeFile(docPath, source)
  await wait(1200)
  win.setSize(1280, 840)
  await settings({ language: 'zh-CN', theme: 'dark', autoSave: false, historyEnabled: false, readOnly: false, sidebarVisible: true })
  await run(`window.__mdview.loadDocument(${JSON.stringify(docPath)})`)
  await wait(350)
  const apple = source.indexOf('苹果')
  await run(`${ctx}.select(${apple}, ${apple + 2})`)
  await press('f', ['control'])
  assert.equal(await run(`document.activeElement.name`), 'search')
  assert.equal(await run(`document.activeElement.value`), '苹果', 'selection seeds search')
  assert.equal(await run(`!!document.querySelector('.live-table')`), false, 'search reveals widget source')
  await press('F3')
  assert.equal(await run(`${ctx}.cursor`), source.indexOf('苹果', apple + 2))
  await press('F3', ['shift'])
  assert.equal(await run(`${ctx}.cursor`), apple)
  await press('F3', ['shift'])
  assert.equal(await run(`${ctx}.cursor`), source.lastIndexOf('苹果'), 'previous wraps into table')
  assert.ok(await run(`document.querySelectorAll('.cm-searchMatch').length`) >= 3)
  await field('search', '不存在的内容')
  await press('F3')
  assert.equal(await run(`document.querySelectorAll('.cm-searchMatch').length`), 0)
  await field('search', '苹果')
  await press('h', ['control'])
  assert.equal(await run(`document.activeElement.name`), 'replace')
  await field('replace', '橙子')
  await press('F3')
  await button('replace')
  assert.equal((await run(`${ctx}.source`)).match(/橙子/g).length, 1)
  await button('replaceAll')
  assert.equal(await run(`${ctx}.source`), source.replaceAll('苹果', '橙子'))
  await run(`document.querySelector('.cm-search input[name=replace]').focus()`)
  await press('b', ['control'])
  await press('z', ['control'])
  assert.equal(await run(`${ctx}.source`), source.replaceAll('苹果', '橙子'), 'search field shortcuts must not edit the document')
  await press('Escape')
  assert.equal(await run(`!!document.querySelector('.cm-search')`), false)
  assert.equal(await run(`!!document.querySelector('.live-table')`), true)
  await press('z', ['control'])
  assert.equal((await run(`${ctx}.source`)).match(/苹果/g).length, 2, 'replace all is one undo step')
  await press('z', ['control'])
  assert.equal(await run(`${ctx}.source`), source)
  await press('f', ['control'])
  await field('search', 'apple')
  await run(`document.querySelector('.cm-search input[name=case]').click(); document.querySelector('.cm-search input[name=word]').click()`)
  await wait(120)
  assert.equal(await run(`document.querySelectorAll('.cm-searchMatch').length`), 3, 'case-sensitive whole words include code and paths')
  await field('search', 'a(pp)le')
  await field('replace', '$1')
  await run(`document.querySelector('.cm-search input[name=re]').click()`)
  await button('replaceAll')
  assert.equal(await run(`${ctx}.source`), source.replace(/\bapple\b/g, 'pp'), 'regexp capture replacement')
  await press('Escape')
  await press('z', ['control'])
  assert.equal(await run(`${ctx}.source`), source)
  await press('f', ['control'])
  await field('search', '[')
  await button('replaceAll')
  assert.equal(await run(`${ctx}.source`), source, 'invalid regexp never edits')
  await settings({ readOnly: true })
  assert.equal(await run(`!!document.querySelector('.cm-search input[name=replace]')`), false)
  await field('search', '苹果')
  await press('F3')
  assert.equal(await run(`${ctx}.source`), source)
  await settings({ readOnly: false, language: 'en' })
  assert.equal(await run(`document.querySelector('.cm-search input[name=search]').placeholder`), 'Find')
  await settings({ language: 'zh-CN' })
  assert.equal(await run(`document.querySelector('.cm-search input[name=search]').placeholder`), '查找')
  await run(`document.querySelectorAll('.cm-search input[type=checkbox]:checked').forEach(el => el.click())`)
  await field('search', '苹果')
  await field('replace', '橙子')
  await press('Escape')
  await press('F3')
  assert.equal(await run(`document.querySelector('.cm-search input[name=search]').value`), '苹果', 'F3 reopens the previous search')
  await shot('01-search-dark')
  await settings({ theme: 'light' })
  await shot('02-search-light')
  win.setSize(720, 640)
  await settings({ theme: 'dark' })
  assert.ok(await run(`(() => { const el = document.querySelector('.cm-search'); return el.scrollWidth <= el.clientWidth })()`), 'search fits narrow windows')
  await shot('03-search-narrow')
  await press('Escape')
  await press('y', ['control', 'alt'])
  assert.equal(await run(`!!document.querySelector('.history-panel')`), true)
  await press('y', ['control', 'alt'])
  await press('s', ['control'])
  assert.equal(await fs.readFile(docPath, 'utf8'), source)
  assert.deepEqual(errors, [])
  console.log('PASS: search, selection, navigation/wrap, table/code/link matches, replace/replace-all/undo, case/word/regexp, read-only, locales, narrow layout, history shortcut and save')
  if (process.argv.includes('--hold')) {
    win.setSize(1280, 840)
    win.center()
    await run(`${ctx}.select(${apple}, ${apple + 2})`)
    await press('f', ['control'])
    await field('search', '苹果')
    await field('replace', '橙子')
    await run(`document.querySelector('.cm-search input[name=search]').focus()`)
    win.focus()
    console.log('READY_FOR_TEST', docPath)
  } else app.quit()
}
app.whenReady().then(() => main().catch(error => { console.error(error); app.exit(1) }))
