/** Real IPC and editor checks; only native dialog choices are scripted. */
const { app, BrowserWindow, dialog } = require('electron')
const path = require('node:path')
const fs = require('node:fs/promises')
const assert = require('node:assert/strict')
const OUT = path.resolve(process.argv[2] || 'design-review/workflow')
require('node:fs').mkdirSync(path.join(OUT, 'documents'), { recursive: true })
app.setPath('userData', path.join(OUT, 'profile'))
app.setPath('documents', path.join(OUT, 'documents'))
const saves = [], choices = [], opens = [], calls = []
dialog.showSaveDialog = async (_window, options) => {
  calls.push(['save', options])
  assert.ok(saves.length, 'unexpected save dialog')
  const filePath = saves.shift()
  return { canceled: filePath === null, filePath }
}
dialog.showMessageBox = async (_window, options) => {
  calls.push(['confirm', options])
  assert.ok(choices.length, 'unexpected unsaved-change dialog')
  return { response: choices.shift(), checkboxChecked: false }
}
dialog.showOpenDialog = async (_window, options) => {
  calls.push(['open', options])
  assert.ok(opens.length, 'unexpected open dialog')
  return { canceled: false, filePaths: [opens.shift()] }
}
require(path.resolve(__dirname, '../out/main/index.js'))
app.removeAllListeners('window-all-closed')
const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms))

async function main() {
  for (let i = 0; i < 80 && !BrowserWindow.getAllWindows().length; i++) await wait(100)
  let win = BrowserWindow.getAllWindows()[0]
  win.setSize(1440, 900)
  const run = code => win.webContents.executeJavaScript(code, true)
  const ctx = 'window.__mdview.editorContext()'
  const until = async (code) => {
    for (let i = 0; i < 80; i++) { if (await run(code)) return; await wait(100) }
    throw new Error(`Timed out: ${code}`)
  }
  const button = async label => {
    await run(`document.querySelector('button[aria-label="${label}"]').click()`)
    await wait(250)
  }
  const edit = async text => { await run(`${ctx}.replace(0, ${ctx}.source.length, ${JSON.stringify(text)})`); await wait(80) }
  const settings = patch => run(`window.__mdview.setSettings(${JSON.stringify(patch)})`)
  const shot = async name => {
    await run('document.fonts.ready.then(() => true)')
    await wait(250)
    await fs.writeFile(path.join(OUT, name + '.png'), (await win.webContents.capturePage()).toPNG())
    console.log('wrote', name)
  }
  await wait(1200)
  await until(`!!document.querySelector('.cm-content')`)
  assert.equal(await run(`${ctx}.docPath`), null)
  assert.equal(await run(`${ctx}.source`), '')
  assert.equal(await run(`document.activeElement.classList.contains('cm-content')`), true)
  await settings({ language: 'zh-CN', autoSave: true, autoSaveDelayMs: 200, historyEnabled: true, historyIntervalMs: 200, autoPair: false })
  await shot('01-blank-ready')
  win.webContents.insertText('# 自由写作\n\n圆体正文，English code 123。')
  await wait(700)
  const draft = await run(`${ctx}.source`)
  assert.match(draft, /自由写作/)
  assert.deepEqual(await fs.readdir(path.join(OUT, 'documents')), [])
  assert.equal(require('node:fs').existsSync(path.join(OUT, 'profile/history')), false, 'draft must not start history timers')
  assert.equal(calls.length, 0)
  await shot('02-unsaved-draft')

  choices.push(2)
  win.close()
  await wait(350)
  assert.equal(win.isDestroyed(), false, 'cancel close must keep the window')
  assert.equal(await run(`${ctx}.source`), draft)
  saves.push(null)
  await run(`${ctx}.save()`)
  assert.equal(await run(`${ctx}.docPath`), null)
  assert.equal(await run(`${ctx}.source`), draft)
  const first = path.join(OUT, 'documents/草稿.md')
  saves.push(first)
  await run(`${ctx}.save()`)
  await until(`${ctx}.docPath === ${JSON.stringify(first)}`)
  assert.equal(await fs.readFile(first, 'utf8'), draft)
  await run(`${ctx}.undo()`)
  await until(`${ctx}.source === ''`)
  await run(`${ctx}.redo()`)
  await until(`${ctx}.source === ${JSON.stringify(draft)}`)
  await edit(draft + '\n\n首次保存后自动写入。')
  await wait(500)
  assert.match(await fs.readFile(first, 'utf8'), /自动写入/)
  assert.equal(calls.filter(c => c[0] === 'save').length, 2)
  await settings({ autoSave: false, historyEnabled: false })
  await edit(draft + '\n手动保存的修改')
  await wait(400)
  assert.doesNotMatch(await fs.readFile(first, 'utf8'), /手动保存/)
  const original = win
  await button('新建文档')
  assert.match(await run(`${ctx}.source`), /手动保存/)
  choices.push(2)
  original.close()
  await wait(250)
  assert.equal(original.isDestroyed(), false)
  choices.push(0)
  original.close()
  await wait(350)
  assert.equal(original.isDestroyed(), true)
  win = BrowserWindow.getAllWindows()[0]
  win.setSize(1440, 900)
  await until(`!!document.querySelector('.cm-content')`)
  await until(`${ctx}.docPath === null && ${ctx}.source === ''`)
  assert.match(await fs.readFile(first, 'utf8'), /手动保存/)

  await edit('保存失败也必须保留这段内容')
  saves.push(path.join(OUT, 'does-not-exist/broken.md'))
  await run(`${ctx}.save()`)
  assert.equal(await run(`${ctx}.docPath`), null)
  assert.match(await run(`document.querySelector('[role="alert"]').textContent`), /保存失败/)
  assert.match(await run(`${ctx}.source`), /必须保留/)
  const failedDraft = win
  await button('新建文档')
  win = BrowserWindow.getAllWindows().find(window => window !== failedDraft)
  assert.ok(win)
  win.setSize(1440, 900)
  choices.push(1)
  failedDraft.close()
  await wait(250)
  assert.equal(failedDraft.isDestroyed(), true)
  await until(`!!document.querySelector('.cm-content')`)
  await until(`${ctx}.source === ''`)

  const document = '---\ntitle: 保留元信息\n---\n# 开始\n\n' + Array.from({length: 30}, (_, i) => `## 第 ${i + 1} 节\n\n圆体正文 English 0123\n\n`).join('') + '## 最后一节'
  const existing = path.join(OUT, 'documents/独立文件.md')
  await fs.writeFile(existing, document)
  opens.push(existing)
  const blank = win
  await button('打开文档')
  win = BrowserWindow.getAllWindows().find(window => window !== blank)
  assert.ok(win)
  win.setSize(1440, 900)
  await until(`!!document.querySelector('.cm-content')`)
  blank.close()
  await until(`${ctx}.docPath === ${JSON.stringify(existing)}`)
  assert.equal(await run(`${ctx}.source`), document)
  await run(`${ctx}.save()`)
  assert.equal(await fs.readFile(existing, 'utf8'), document, 'saving must preserve frontmatter')
  await settings({ sidebarVisible: true, outlineVisible: true })
  const jumpLast = async () => {
    await run(`Array.from(document.querySelectorAll('.outline__jump')).find(b=>b.title==='最后一节').click()`)
    await wait(400)
    const top = await run(`(()=>{const line=Array.from(document.querySelectorAll('.cm-line')).find(e=>e.textContent==='最后一节'); return line.getBoundingClientRect().top-document.querySelector('.cm-scroller').getBoundingClientRect().top})()`)
    assert.ok(top >= -1 && top <= 64, `outline target must be at the top, got ${top}`)
  }
  await jumpLast()
  await shot('03-outline-top')
  await settings({ fontSize: 23 })
  await jumpLast()
  await settings({ fontSize: 17 })
  assert.equal(await run(`document.fonts.check('17px "MDView Rounded"', '圆体正文')`), true)
  assert.equal(await run(`(()=>{const c=document.createElement('canvas').getContext('2d');c.font='17px '+getComputedStyle(document.querySelector('.cm-content')).fontFamily;return Math.abs(c.measureText('iiii').width-c.measureText('WWWW').width)<0.1})()`), true, 'English must be monospaced')

  await button('设置')
  await shot('04-settings-fonts')
  await run(`Array.from(document.querySelectorAll('.settings__tab')).find(b=>b.textContent==='文档与保存').click()`)
  assert.equal(await run(`!!document.querySelector('button[aria-label="自动保存"]')`), true)
  await shot('05-settings-saving')
  await run(`Array.from(document.querySelectorAll('.settings__tab')).find(b=>b.textContent==='快捷键').click()`)
  await run(`(()=>{const s=document.querySelector('select[aria-label="快捷键功能分类"]');s.value='file';s.dispatchEvent(new Event('change',{bubbles:true}))})()`)
  await wait(150)
  assert.match(await run(`document.querySelector('.shortcuts-settings').textContent`), /新建文档/)
  assert.doesNotMatch(await run(`document.querySelector('.shortcuts-settings').textContent`), /加粗/)
  await shot('06-settings-shortcuts')
  await settings({ theme: 'light', fontRead: 'Arial' })
  win.setSize(900, 800)
  await shot('07-settings-light-narrow')
  await run('window.__mdview.closePanel()')
  await run(`${ctx}.save()`)
  await wait(1400)
  win.webContents.reload()
  await wait(1600)
  await until(`!!document.querySelector('.cm-content')`)
  assert.match(await run(`document.documentElement.style.getPropertyValue('--font-read')`), /Arial/)
  assert.equal(await run(`${ctx}.source`), document)
  await settings({ fontRead: null, theme: 'dark' })
  assert.equal(await run(`document.documentElement.style.getPropertyValue('--font-read')`), '')
  await edit(document + '\n关闭时保存')
  choices.push(0)
  win.close()
  for (let i = 0; i < 50 && !win.isDestroyed(); i++) await wait(100)
  assert.equal(win.isDestroyed(), true, 'saving on close must finish before the window closes')
  assert.match(await fs.readFile(existing, 'utf8'), /关闭时保存/)
  assert.deepEqual([saves.length, choices.length, opens.length], [0, 0, 0])
  console.log('PASS: blank startup, draft no IO/timers, save/cancel/failure/undo, autosave, new/open/close guards, frontmatter, outline top, grouped settings, fonts and persistence')
  app.exit(0)
}
app.whenReady().then(main).catch(error => { console.error(error); app.exit(1) })
